restaurant/urls.py
from django.urls import path

from restaurant.views import (IndexView,
                              SignUpView,

                              DishListView,
                              DishCreateView,
                              DishDetailView,
                              DishUpdateView,
                              DishDeleteView,

                              DishTypeListView,
                              DishTypeDetailView,
                              DishTypeCreateView,
                              DishTypeUpdateView,
                              DishTypeDeleteView,
                              DishUpdateCookView,

                              CookListView,
                              CookDetailView,
                              CookCreateView,
                              CookUpdateView,
                              CookDeleteView)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),

    path("dishes/",
         DishListView.as_view(),
         name="dish-list"),
    path("dishes/<int:pk>/",
         DishDetailView.as_view(),
         name="dish-detail"),
    path("dishes/create/",
         DishCreateView.as_view(),
         name="dish-create"),
    path("dishes/<int:pk>/update/",
         DishUpdateView.as_view(),
         name="dish-update"),
    path("dishes/<int:pk>/delete/",
         DishDeleteView.as_view(),
         name="dish-delete"),
    path("dishes/<int:pk>/update-cook/",
         DishUpdateCookView.as_view(),
         name="dish-update-cook"),

    path("dish-types/",
         DishTypeListView.as_view(),
         name="dish-type-list"),
    path("dish-types/<int:pk>/",
         DishTypeDetailView.as_view(),
         name="dish-type-detail"),
    path("dish-types/create/",
         DishTypeCreateView.as_view(),
         name="dish-type-create"),
    path("dish-types/<int:pk>/update/",
         DishTypeUpdateView.as_view(),
         name="dish-type-update"),
    path("dish-types/<int:pk>/delete/",
         DishTypeDeleteView.as_view(),
         name="dish-type-delete"),

    path("cooks/",
         CookListView.as_view(),
         name="cook-list"),
    path("cooks/<int:pk>/",
         CookDetailView.as_view(),
         name="cook-detail"),
    path("cooks/create/",
         CookCreateView.as_view(),
         name="cook-create"),
    path("cooks/<int:pk>/update/",
         CookUpdateView.as_view(),
         name="cook-update"),

    path("cooks/<int:pk>/delete/",
         CookDeleteView.as_view(),
         name="cook-delete"),

    path("signup/", SignUpView.as_view(), name="signup")
]


app_name = "restaurant"

restaurant_service/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("registration/", include("django.contrib.auth.urls"), ),

    path("__debug__/", include(debug_toolbar.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<nav>
  <ul class="topmenu">
    {% if user.is_authenticated %}
    <li><a class="down" href="{% url 'restaurant:cook-detail' pk=user.id %}">User: <strong>{{ user.username }}</strong></a>
      <ul class="submenu">
        {% if user.is_superuser %}
        <li><a href="http://127.0.0.1:8000/admin/">Admin panel</a></li>
        {% endif %}
        <li><a href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </li>
    {% else %}
      <a href="{% url 'login' %}">Login</a>
    {% endif %}

    <br>

    <li><a href="{% url 'restaurant:index' %}">Home</a></li>
    <li><a href="{% url 'restaurant:dish-list' %}">All dishes</a></li>
    <li><a href="{% url 'restaurant:cook-list' %}">All cooks</a></li>
    <li><a href="{% url 'restaurant:dish-type-list' %}">All dish types</a></li>

    <br>
    {% if user.is_authenticated %}
      <li><a href="{% url 'restaurant:dish-create' %}">Add dish</a></li>
    {% endif %}
    {% if user.is_superuser %}
      <li><a href="{% url 'restaurant:dish-type-create' %}">Add dish type</a></li>
      <li><a href="{% url 'restaurant:cook-create' %}">Add cook</a></li>
    {% endif %}
  </ul>
</nav>