restaurant/urls.py
from django.urls import path

from restaurant.views import (IndexView,
                              SignUpView,

                              DishListView,
                              DishCreateView,
                              DishDetailView,
                              DishUpdateView,
                              DishDeleteView,

                              DishTypeListView,
                              DishTypeDetailView,
                              DishTypeCreateView,
                              DishTypeUpdateView,
                              DishTypeDeleteView,
                              DishUpdateCookView,

                              CookListView,
                              CookDetailView,
                              CookCreateView,
                              CookUpdateView,
                              CookDeleteView)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),

    path("dishes/",
         DishListView.as_view(),
         name="dish-list"),
    path("dishes/<int:pk>/",
         DishDetailView.as_view(),
         name="dish-detail"),
    path("dishes/create/",
         DishCreateView.as_view(),
         name="dish-create"),
    path("dishes/<int:pk>/update/",
         DishUpdateView.as_view(),
         name="dish-update"),
    path("dishes/<int:pk>/delete/",
         DishDeleteView.as_view(),
         name="dish-delete"),
    path("dishes/<int:pk>/update-cook/",
         DishUpdateCookView.as_view(),
         name="dish-update-cook"),

    path("dish-types/",
         DishTypeListView.as_view(),
         name="dish-type-list"),
    path("dish-types/<int:pk>/",
         DishTypeDetailView.as_view(),
         name="dish-type-detail"),
    path("dish-types/create/",
         DishTypeCreateView.as_view(),
         name="dish-type-create"),
    path("dish-types/<int:pk>/update/",
         DishTypeUpdateView.as_view(),
         name="dish-type-update"),
    path("dish-types/<int:pk>/delete/",
         DishTypeDeleteView.as_view(),
         name="dish-type-delete"),

    path("cooks/",
         CookListView.as_view(),
         name="cook-list"),
    path("cooks/<int:pk>/",
         CookDetailView.as_view(),
         name="cook-detail"),
    path("cooks/create/",
         CookCreateView.as_view(),
         name="cook-create"),
    path("cooks/<int:pk>/update/",
         CookUpdateView.as_view(),
         name="cook-update"),

    path("cooks/<int:pk>/delete/",
         CookDeleteView.as_view(),
         name="cook-delete"),

    path("signup/", SignUpView.as_view(), name="signup")
]


app_name = "restaurant"

restaurant_service/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("registration/", include("django.contrib.auth.urls"), ),

    path("__debug__/", include(debug_toolbar.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurant/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]
        verbose_name = "Dish Type"
        verbose_name_plural = "Dish Types"

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("restaurant:dish-type-detail", args=[str(self.id)])


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        ordering = ["username"]

    def __str__(self) -> str:
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("restaurant:cook-detail", args=[str(self.id)])


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    dish_type = models.ForeignKey(DishType,
                                  on_delete=models.CASCADE,
                                  related_name="dishes")
    cooks = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                   related_name="dishes")

    class Meta:
        ordering = ["name"]
        verbose_name = "Dish"
        verbose_name_plural = "Dishes"

    def __str__(self) -> str:
        return (f"{self.name} (price: "
                f"{self.price}, type: {self.dish_type.name})")

    def get_absolute_url(self):
        return reverse("restaurant:dish-detail", args=[str(self.id)])

restaurant/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import ValidationError

from restaurant.models import Dish, DishType
import re


class CookCreationForm(UserCreationForm):
    username = forms.CharField(
        max_length=255,
        widget=forms.TextInput(
            attrs={"placeholder": "*Username: "}
        ),
        label="")
    first_name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(
            attrs={"placeholder": "First name: "}
        ),
        label="")
    last_name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(
            attrs={"placeholder": "Last name: "}
        ),
        label="")
    years_of_experience = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={"placeholder": "*Years of experience:"}
        ),
        label="")

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ("first_name",
                                                 "last_name",
                                                 "years_of_experience")

    def clean_years_of_experience(self):
        years_of_experience = self.cleaned_data["years_of_experience"]
        if years_of_experience < 0:
            raise ValidationError("Experience can't be a negative number!")
        if years_of_experience > 60:
            raise ValidationError("Cook can't have that much of experience!")
        return years_of_experience


class CookUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["username", "years_of_experience", "first_name", "last_name"]


class DishForm(forms.ModelForm):
    name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(
            attrs={"placeholder": "*Name: "}
        ),
        label="")
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={"placeholder": "*Description: "}
        ),
        label="")
    price = forms.DecimalField(
        max_digits=5,
        decimal_places=2,
        widget=forms.NumberInput(
            attrs={"placeholder": "*Price:"}
        ),
        label="")
    dish_type = forms.ModelChoiceField(
        queryset=DishType.objects.all(),
        widget=forms.Select(
            attrs={"placeholder": "Choose the dish type"}
        ),
        empty_label="Choose the dish type")
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishTypeForm(forms.ModelForm):
    name = forms.CharField(
        max_length=255,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "*Name"}
        )
    )

    class Meta:
        model = DishType
        fields = "__all__"

    def clean_name(self):
        pattern = r"^[a-zA-Z\s]+$"
        name = self.cleaned_data["name"]
        if not re.match(pattern, name):
            raise ValidationError("Name can't contain digits!")
        return name


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search the dish by name..."}
        )
    )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search the dish by username..."}
        )
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search the dish by name..."}
        )
    )

restaurant/views.py
from django.contrib.auth import get_user_model, login, authenticate
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View, generic

from restaurant.forms import (CookCreationForm,
                              CookSearchForm,
                              CookUpdateForm,
                              DishForm,
                              DishSearchForm,
                              DishTypeForm,
                              DishTypeSearchForm)
from restaurant.models import Cook, Dish, DishType


class IndexView(View):
    @staticmethod
    def get(request):
        return render(request, "restaurant/index.html")


class DishListView(generic.ListView):
    model = Dish
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(DishListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = DishSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        queryset = Dish.objects.select_related("dish_type")
        form = DishSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class DishDetailView(generic.DetailView):
    model = Dish
    queryset = Dish.objects.prefetch_related("cooks")


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    template_name = "restaurant/dish_form.html"


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    template_name = "restaurant/dish_form.html"


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("restaurant:dish-list")
    template_name = "restaurant/dish_confirm_delete.html"


class DishTypeListView(generic.ListView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "restaurant/dish_type_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(DishTypeListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = DishTypeSearchForm(initial={
            "name": name
        })

        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = DishTypeSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class DishTypeDetailView(generic.DetailView):
    template_name = "restaurant/dish_type_detail.html"
    context_object_name = "dish_type"
    model = DishType
    queryset = DishType.objects.all()


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    form_class = DishTypeForm
    context_object_name = "dish_type"
    template_name = "restaurant/dish_type_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    context_object_name = "dish_type"
    form_class = DishTypeForm
    template_name = "restaurant/dish_type_form.html"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    context_object_name = "dish_type"
    success_url = reverse_lazy("restaurant:dish-type-list")
    template_name = "restaurant/dish_type_confirm_delete.html"


class CookListView(generic.ListView):
    model = get_user_model()
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(CookListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = CookSearchForm(initial={
            "username": username
        })

        return context

    def get_queryset(self):
        queryset = get_user_model().objects.all()
        form = CookSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class CookDetailView(generic.DetailView):
    model = get_user_model()
    queryset = Cook.objects.prefetch_related("dishes__dish_type")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = get_user_model()
    form_class = CookCreationForm
    template_name = "restaurant/cook_form.html"


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    form_class = CookUpdateForm
    template_name = "restaurant/cook_form.html"


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = get_user_model()
    success_url = reverse_lazy("restaurant:cook-list")
    template_name = "restaurant/cook_confirm_delete.html"


class SignUpView(generic.CreateView):
    model = get_user_model()
    form_class = CookCreationForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy("restaurant:index")

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Your account is created successfully")
        new_user = authenticate(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password1"]
        )

        login(self.request, new_user)
        return redirect("restaurant:index")


class DishUpdateCookView(LoginRequiredMixin, generic.UpdateView):
    def post(self, request, *args, **kwargs):
        cook = request.user
        dish = get_object_or_404(Dish, pk=kwargs["pk"])

        if cook in dish.cooks.all():
            dish.cooks.remove(cook)
        else:
            dish.cooks.add(cook)
        return redirect("restaurant:dish-detail", pk=kwargs["pk"])

templates/restaurant/cook_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  <title>Delete account</title>
{% endblock %}

{% block content %}
  {% if user.is_superuser or user.id is cook.id %}
    <h1>Delete account</h1>
    {% if user.is_superuser %}
  <h4>Are you sure you want to delete this account: <strong>{{ cook }}</strong>?</h4>
      {% else %}
        <h4>Are you sure you want to delete your account?</h4>
      {% endif %}

  <form action="" method="post">
    {% csrf_token %}
    <input id="delete-btn" type="submit" value="Yes, delete" class="btn btn-danger">
    <a href="{% url 'restaurant:cook-detail' pk=cook.id %}" class="btn btn-primary">No, cancel</a>

  </form>
  {% else %}
    <h1>You don't have permission to delete users!</h1>
    <a class="btn btn-primary" href="{% url 'restaurant:index' %}">Back to Home</a>
  {% endif %} 


{% endblock %}

templates/restaurant/cook_detail.html
{% extends 'base.html' %}

{% block title %}
  <title>{{ cook.first_name }} {{ cook.last_name }}</title>
{% endblock %}

{% block content %}
  <h2>
    Full name: {{ cook.first_name }} {{ cook.last_name }}
    {% if user.is_superuser or user.id == cook.id %}
      <a class="btn btn-primary" href="{% url 'restaurant:cook-update' pk=cook.id %}">Edit</a>
      <a class="btn btn-danger" href="{% url 'restaurant:cook-delete' pk=cook.id %}">Delete</a>
    {% endif %}
  </h2>
  <h5>Username: {{ cook.username }}</h5>
  <p><strong>Years of experience: {{ cook.years_of_experience }}</strong></p>

  <div class="ml-3">
    <h3>Dishes</h3>
    {% for dish in cook.dishes.all %}
      <hr>
      <p class="text-muted"><strong>ID: </strong>{{ dish.id }}</p>
      <p><strong>Name: </strong><a class="list-item" href="{{ dish.get_absolute_url }}">{{ dish.name }}</a></p>
      <p><strong>Price: </strong>{{ dish.price }}</p>
      <p><strong>Dish type: </strong>{{ dish.dish_type }}</p>
    {% empty %}
      <h5>No dishes!</h5>
    {% endfor %}

  </div>
{% endblock %}

templates/restaurant/cook_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
  <title>{{ object|yesno:"Update,Create" }} cook</title>
{% endblock %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} cook</h1>

  <form method="post" action="" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Create">
    <a class="btn btn-danger" onclick="goBack()">Cancel</a>
  </form>
{% endblock %}

templates/restaurant/cook_list.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
  <title>Cooks</title>
{% endblock %}

{% block content %}
  <h1>
    Cooks
  </h1>
  {% if user.is_superuser %}
  <a class="btn btn-primary" href="{% url 'restaurant:cook-create' %}">Add the cook</a>
  <hr>
  {% endif %}
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔍">

  {% if cook_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>Full name</th>
        <th>Years of experience</th>
        {% if user.is_superuser %}
        <th>Update</th>
        <th>Delete</th>
        {% endif %}
      </tr>
      {% for cook in cook_list %}
        <tr>
          <td>
            {{ cook.id }}
          </td>
          <td>
            <a class="list-item" href="{{ cook.get_absolute_url }}">{{ cook.username }}</a>
          </td>
          <td>
            {{ cook.first_name }} {{ cook.last_name }}
          </td>
          <td>
            {{ cook.years_of_experience|default_if_none:"" }}
          </td>
          {% if user.is_superuser %}
            <td>
              <a class="update" href="{% url 'restaurant:cook-update' pk=cook.id %}">Update</a>
            </td>
            <td>
              <a class="delete" href="{% url 'restaurant:cook-delete' pk=cook.id %}">Delete</a>
            </td>
          {% endif %}

        </tr>
      {% endfor %}

    </table>
  {% else %}
    <br>
    <p>There are no cooks!</p>
  {% endif %}
  </form>
{% endblock %}

templates/restaurant/dish_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete dish</h1>
  <h4>Are you sure you want to delete this dish: <strong>{{ dish }}</strong>? It seems pretty tasty</h4>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a onclick="goBack()" class="btn btn-primary">No, cancel</a>
  </form>

{% endblock %}

templates/restaurant/dish_detail.html
{% extends 'base.html' %}

{% block title %}
  <title>{{ dish.title }}</title>
{% endblock %}

{% block content %}
  <h2>
    Name: {{ dish.name }}
    {% if user.is_authenticated and user in dish.cooks.all %}
    <a class="btn btn-primary" href="{% url 'restaurant:dish-update' pk=dish.id %}">Edit</a>
    <a class="btn btn-danger" href="{% url 'restaurant:dish-delete' pk=dish.id %}">Delete</a>
    {% elif user.is_superuser %}
      <a class="btn btn-primary" href="{% url 'restaurant:dish-update' pk=dish.id %}">Edit</a>
      <a class="btn btn-danger" href="{% url 'restaurant:dish-delete' pk=dish.id %}">Delete</a>
    {% endif %}
  </h2>
  <p><strong>Price: </strong>${{ dish.price }}</p>
  <p><strong>Dish type: </strong>{{ dish.dish_type.name }}</p>
  <p><strong>Description: </strong>{{ dish.description }}</p>

  <div class="ml-3">
    <h3>Cooks</h3>

    <form method="post" action="{% url 'restaurant:dish-update-cook' pk=dish.id %}">
      {% csrf_token %}
      {% if user in dish.cooks.all %}
        <input class="btn btn-danger" type="submit" value="I can't cook this dish">
      {% else %}
        <input class="btn btn-primary" type="submit" value="I can cook this dish">
      {% endif %}

    </form>
    {% for cook in dish.cooks.all %}
      <hr>
      <p class="text-muted"><strong>ID: </strong>{{ cook.id }}</p>
      <p><strong>Username: </strong><a href="{{ cook.get_absolute_url }}">{{ cook.username }}</a></p>
      <p><strong>Full name: </strong>{{ cook.first_name }} {{ cook.last_name }}</p>
    {% empty %}
      <h5>No dishes!</h5>
    {% endfor %}

  </div>
{% endblock %}

templates/restaurant/dish_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
  <title>{{ object|yesno:"Update,Create" }} dish</title>
{% endblock %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>

  <form method="post" action="" novalidate>
    {% csrf_token %}
    {{ form|crispy}}

    <input class="btn btn-primary" type="submit" value="Create">
    <a onclick="goBack()" class="btn btn-danger">Cancel</a>
  </form>
{% endblock %}

templates/restaurant/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  <title>Dishes</title>
{% endblock %}

{% block content %}
  <h1>
    Dishes
  </h1>
  {% if user.is_authenticated %}
  <a class="btn btn-primary" href="{% url 'restaurant:dish-create' %}">Add the dish</a>
  <hr>
  {% endif %}
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔍">
  {% if dish_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Dish type</th>
        {% if user.is_superuser %}
        <th>Update</th>
        <th>Delete</th>
        {% endif %}

      </tr>
    {% for dish in dish_list %}
      <tr>
        <td>
          {{ dish.id }}
        </td>
        <td>
          <a class="list-item" href="{% url 'restaurant:dish-detail' pk=dish.id %}">{{ dish.name }}</a>
        </td>
        <td>
          {{ dish.description|truncatewords:15 }}
        </td>
        <td>
          ${{ dish.price }}
        </td>
        <td>
          {{ dish.dish_type }}
        </td>
        {% if user.is_superuser %}
          <td>
            <a class="update" href="{% url 'restaurant:dish-update' pk=dish.id %}">Update</a>
          </td>
          <td>
            <a class="delete" href="{% url 'restaurant:dish-delete' pk=dish.id %}">Delete</a>
          </td>
        {% endif %}
      </tr>
    {% endfor %}

    </table>

  {% endif %}
  </form>
{% endblock %}

templates/restaurant/dish_type_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete dish type</h1>
  <h4>Are you sure you want to delete this dish type: <strong>{{ dish_type }}</strong>?</h4>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a onclick="goBack()" class="btn btn-primary">No, cancel</a>
  </form>

{% endblock %}

templates/restaurant/dish_type_detail.html
{% extends 'base.html' %}

{% block title %}
  <title>{{ dish_type.name }}</title>
{% endblock %}

{% block content %}
  <h2>
    Name: {{ dish_type.name }}
    {% if user.is_superuser %}
    <a class="btn btn-primary" href="{% url 'restaurant:dish-type-update' pk=dish_type.id %}">Edit</a>
    <a class="btn btn-danger" href="{% url 'restaurant:dish-type-delete' pk=dish_type.id %}">Delete</a>
    {% endif %}
  </h2>

  <div class="ml-3">
    <h3>Dishes with this dish type:</h3>
    {% for dish in dish_type.dishes.all %}
      <hr>
      <p class="text-muted"><strong>ID: </strong>{{ dish.id }}</p>
      <p><strong>Full name: </strong><a href="{% url 'restaurant:dish-detail' pk=dish.id %}">{{ dish.name }} (price: {{ dish.price }})</a>
      </p>
    {% empty %}
      <h5>No dish types!</h5>
    {% endfor %}

  </div>
{% endblock %}

templates/restaurant/dish_type_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
  <title>{{ object|yesno:"Update,Create" }} dish type</title>
{% endblock %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish type</h1>

  <form method="post" action="" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Create">
    <a onclick="goBack()" class="btn btn-danger">Cancel</a>
  </form>
{% endblock %}

templates/restaurant/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  <title>Dish Types</title>
{% endblock %}

{% block content %}
  <h1>
    Dish Types
  </h1>
  {% if user.is_superuser %}
  <a class="btn btn-primary" href="{% url 'restaurant:dish-type-create' %}">Add the dish type</a>
    <hr>
  {% endif %}
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔍">
  {% if dish_type_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        {% if user.is_superuser %}
        <th>Update</th>
        <th>Delete</th>
        {% endif %}

      </tr>
    {% for dish_type in dish_type_list %}
      <tr>
        <td>
          {{ dish_type.id }}
        </td>
        <td>
          <a class="list-item" href="{% url 'restaurant:dish-type-detail' pk=dish_type.id %}">{{ dish_type.name }}</a>
        </td>
        {% if user.is_superuser %}
        <td>
          <a class="update" href="{% url 'restaurant:dish-type-update' pk=dish_type.id %}">Update</a>
        </td>
        <td>
          <a class="delete" href="{% url 'restaurant:dish-type-delete' pk=dish_type.id %}">Delete</a>
        </td>
        {% endif %}
      </tr>
    {% endfor %}

    </table>

  {% endif %}
  </form>
{% endblock %}

templates/restaurant/index.html
{% extends "base.html" %}

{% block title %}
  <title>Home Page</title>
{% endblock %}

{% block content %}
   <h1 class="welcome-big">Welcome</h1>
  <hr class="horizontal-line">
  <p class="welcome-little">Our website offers a platform for chefs to register, share recipes, and explore a diverse range of dishes..</p>

  <p class="welcome-text">
    Welcome to our website! Here, you can register as a chef, add your delicious recipes, and explore
    <a href="{% url 'restaurant:dish-list' %}">a wide range of culinary delights</a>
    . Whether you're a professional chef or a passionate home cook, this platform is designed to showcase your culinary skills and share your mouthwatering creations with
    <a href="{% url 'restaurant:cook-list' %}">food enthusiasts from around the world</a>.
  </p>
  <br>
  <p class="welcome-text">Registering as a chef is a simple process that allows you to
    {% if not user.is_authenticated %}
    <a href="{% url 'restaurant:signup' %}">create your own personalized account</a>
    {% else %}
      create your own personalized account
    {% endif %}
    . Once registered, you'll have access to your dashboard, where you can manage your profile and add your unique recipes to our ever-growing collection of dishes.</p>
  <br>
  <p class="welcome-text">Adding a new recipe is a breeze! Simply provide the dish's name, a captivating description, and a list of ingredients and cooking instructions. You can also upload enticing images to give fellow users a visual feast of what's in store. Sharing your culinary expertise has never been this easy!</p>
  <br>
  <p class="welcome-text">Are you curious about a particular recipe? Click on any dish's name to view its detailed description. Discover the story behind the creation, explore the flavors, and find useful tips and tricks from the chef who crafted the masterpiece.</p>
  <br>
  <p class="welcome-text">Whether you're here to find inspiration for your next culinary adventure or to share your passion for cooking, we hope you enjoy this platform dedicated to celebrating the art of food. Join our community of talented chefs and enthusiastic food lovers today!</p>
{% endblock %}